### ISSUE TITLE
Buttons show alt

### ISSUE THREAD

**Issue by lil5** [dom111/webdav-js#22]
![screenshot_2018-11-13 - localhost 8080](https://user-images.githubusercontent.com/17646836/48401008-46f57680-e728-11e8-8cd5-fcb61bc21d78.png)

Fix
```css
ul.list li a.copy, ul.list li a.delete, ul.list li a.download, ul.list li a.move, ul.list li a.rename {
  color: transparent;
}
```
