### ISSUE TITLE
Open PDFs within browser window/lightbox

### ISSUE THREAD

**Issue by nielll** [dom111/webdav-js#53]
Hi Dom, 

I just discovered another little detail to improve: When you click a pdf it directly downloads it instead of trying to open it in browser.

**Comment by nielll** [comment]
![picture](https://niel.site/share/files/samplepicture.png)

Background color might be too dark with transparent images

```css
.basicLightbox {
    background: rgba(0,0,0,.8);
}
```
![picture](https://niel.site/share/files/samplepicture2.png)

```css
.basicLightbox {
    background: rgba(0,0,0,.5);
}
```

rgba set to 0.5 is already a lot better.
