### ISSUE TITLE
Lighten overlay backround

### ISSUE THREAD

**Issue by dom111** [dom111/webdav-js#54]
Another detail: when you open an Image with transparent background, the html background is almost too black.

![picture](https://niel.site/share/files/samplepicture.png)

Background color might be too dark with transparent images

```css
.basicLightbox {
    background: rgba(0,0,0,.8);
}
```
![picture](https://niel.site/share/files/samplepicture2.png)

```css
.basicLightbox {
    background: rgba(0,0,0,.5);
}
```

rgba set to 0.5 is already a lot better.

_Originally posted by @nielll in https://github.com/dom111/webdav-js/issues/53#issuecomment-560471545_
